"""Prompts for synthetic open_work + masonry balcony railing crops (FLUX.2).

Hard constraints (every prompt):
- viewpoint: street-side photo of the facade / balcony (never from on the balcony)
- openings: gaps must exist between posts (balusters, pierced panel, grille, etc.)
- framing: medium facade crop — whole window behind the balcony visible
- level: floors 2–10; mix of frontal and strong upward / looking-up perspective

Flexible:
- material: stone, concrete block, or concrete
- slab shape and baluster / pierced-panel styles
"""

from __future__ import annotations

MASONRY_OPENWORK_PROMPTS: list[str] = [
    'street-side medium shot of a 2nd-floor balcony, beige stucco facade, rectangular concrete slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'street view facade crop of a 3rd-floor balcony, grey concrete facade, slightly elliptical stone balcony, classical balusters matching cornice and brackets, openings between posts, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from the sidewalk looking up at a 4th-floor balcony, strong perspective foreshortening, red brick facade, semicircular concrete balcony, square posts and rectangular balusters with clear open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'street-level sidewalk looking upward toward a 5th-floor balcony, tall facade perspective, white painted facade, elliptical limestone balcony, ornate classical balusters, open voids between balusters, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'angled street photo looking up at a 6th-floor balcony, perspective foreshortening, ochre plaster facade, triangular-plan concrete balcony, thick posts with pierced precast panel openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'frontal street crop of a 7th-floor balcony, dark charcoal modern facade, hexagonal stone balcony slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'sidewalk street-side view of a 8th-floor balcony, sandstone historic facade, trapezoidal concrete balcony, classical balusters matching large brackets, see-through openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from across the street, looking up at a 9th-floor balcony with perspective, pale blue apartment facade, white concrete balcony, classical masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'low-angle street photo of a 10th-floor balcony, strong upward perspective, terracotta tiled facade accents, semicircular concrete balcony, heavy posts and geometric precast grille openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'medium facade crop from the sidewalk of a 2nd-floor balcony, limestone classical facade, slightly oval stone balcony, square posts and rectangular balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'street-side medium shot of a 3rd-floor balcony, beige stucco facade, rectangular concrete slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'street view facade crop of a 4th-floor balcony, grey concrete facade, slightly elliptical stone balcony, classical balusters matching cornice and brackets, openings between posts, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from the sidewalk looking up at a 5th-floor balcony, strong perspective foreshortening, red brick facade, semicircular concrete balcony, square posts and rectangular balusters with clear open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'street-level sidewalk looking upward toward a 6th-floor balcony, tall facade perspective, white painted facade, elliptical limestone balcony, ornate classical balusters, open voids between balusters, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'angled street photo looking up at a 7th-floor balcony, perspective foreshortening, ochre plaster facade, triangular-plan concrete balcony, thick posts with pierced precast panel openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'frontal street crop of a 8th-floor balcony, dark charcoal modern facade, hexagonal stone balcony slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'sidewalk street-side view of a 9th-floor balcony, sandstone historic facade, trapezoidal concrete balcony, classical balusters matching large brackets, see-through openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from across the street, looking up at a 10th-floor balcony with perspective, pale blue apartment facade, white concrete balcony, classical masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'low-angle street photo of a 2nd-floor balcony, strong upward perspective, terracotta tiled facade accents, semicircular concrete balcony, heavy posts and geometric precast grille openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'medium facade crop from the sidewalk of a 3rd-floor balcony, limestone classical facade, slightly oval stone balcony, square posts and rectangular balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'street-side medium shot of a 4th-floor balcony, beige stucco facade, rectangular concrete slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'street view facade crop of a 5th-floor balcony, grey concrete facade, slightly elliptical stone balcony, classical balusters matching cornice and brackets, openings between posts, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from the sidewalk looking up at a 6th-floor balcony, strong perspective foreshortening, red brick facade, semicircular concrete balcony, square posts and rectangular balusters with clear open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'street-level sidewalk looking upward toward a 7th-floor balcony, tall facade perspective, white painted facade, elliptical limestone balcony, ornate classical balusters, open voids between balusters, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'angled street photo looking up at a 8th-floor balcony, perspective foreshortening, ochre plaster facade, triangular-plan concrete balcony, thick posts with pierced precast panel openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'frontal street crop of a 9th-floor balcony, dark charcoal modern facade, hexagonal stone balcony slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'sidewalk street-side view of a 10th-floor balcony, sandstone historic facade, trapezoidal concrete balcony, classical balusters matching large brackets, see-through openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from across the street, looking up at a 2nd-floor balcony with perspective, pale blue apartment facade, white concrete balcony, classical masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'low-angle street photo of a 3rd-floor balcony, strong upward perspective, terracotta tiled facade accents, semicircular concrete balcony, heavy posts and geometric precast grille openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'medium facade crop from the sidewalk of a 4th-floor balcony, limestone classical facade, slightly oval stone balcony, square posts and rectangular balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'street-side medium shot of a 5th-floor balcony, beige stucco facade, rectangular concrete slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'street view facade crop of a 6th-floor balcony, grey concrete facade, slightly elliptical stone balcony, classical balusters matching cornice and brackets, openings between posts, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from the sidewalk looking up at a 7th-floor balcony, strong perspective foreshortening, red brick facade, semicircular concrete balcony, square posts and rectangular balusters with clear open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'street-level sidewalk looking upward toward a 8th-floor balcony, tall facade perspective, white painted facade, elliptical limestone balcony, ornate classical balusters, open voids between balusters, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'angled street photo looking up at a 9th-floor balcony, perspective foreshortening, ochre plaster facade, triangular-plan concrete balcony, thick posts with pierced precast panel openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'frontal street crop of a 10th-floor balcony, dark charcoal modern facade, hexagonal stone balcony slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'sidewalk street-side view of a 2nd-floor balcony, sandstone historic facade, trapezoidal concrete balcony, classical balusters matching large brackets, see-through openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from across the street, looking up at a 3rd-floor balcony with perspective, pale blue apartment facade, white concrete balcony, classical masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'low-angle street photo of a 4th-floor balcony, strong upward perspective, terracotta tiled facade accents, semicircular concrete balcony, heavy posts and geometric precast grille openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'medium facade crop from the sidewalk of a 5th-floor balcony, limestone classical facade, slightly oval stone balcony, square posts and rectangular balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'street-side medium shot of a 6th-floor balcony, beige stucco facade, rectangular concrete slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'street view facade crop of a 7th-floor balcony, grey concrete facade, slightly elliptical stone balcony, classical balusters matching cornice and brackets, openings between posts, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from the sidewalk looking up at a 8th-floor balcony, strong perspective foreshortening, red brick facade, semicircular concrete balcony, square posts and rectangular balusters with clear open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'street-level sidewalk looking upward toward a 9th-floor balcony, tall facade perspective, white painted facade, elliptical limestone balcony, ornate classical balusters, open voids between balusters, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'angled street photo looking up at a 10th-floor balcony, perspective foreshortening, ochre plaster facade, triangular-plan concrete balcony, thick posts with pierced precast panel openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'frontal street crop of a 2nd-floor balcony, dark charcoal modern facade, hexagonal stone balcony slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'sidewalk street-side view of a 3rd-floor balcony, sandstone historic facade, trapezoidal concrete balcony, classical balusters matching large brackets, see-through openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from across the street, looking up at a 4th-floor balcony with perspective, pale blue apartment facade, white concrete balcony, classical masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'low-angle street photo of a 5th-floor balcony, strong upward perspective, terracotta tiled facade accents, semicircular concrete balcony, heavy posts and geometric precast grille openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'medium facade crop from the sidewalk of a 6th-floor balcony, limestone classical facade, slightly oval stone balcony, square posts and rectangular balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'street-side medium shot of a 7th-floor balcony, beige stucco facade, rectangular concrete slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'street view facade crop of a 8th-floor balcony, grey concrete facade, slightly elliptical stone balcony, classical balusters matching cornice and brackets, openings between posts, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from the sidewalk looking up at a 9th-floor balcony, strong perspective foreshortening, red brick facade, semicircular concrete balcony, square posts and rectangular balusters with clear open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'street-level sidewalk looking upward toward a 10th-floor balcony, tall facade perspective, white painted facade, elliptical limestone balcony, ornate classical balusters, open voids between balusters, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'angled street photo looking up at a 2nd-floor balcony, perspective foreshortening, ochre plaster facade, triangular-plan concrete balcony, thick posts with pierced precast panel openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'frontal street crop of a 3rd-floor balcony, dark charcoal modern facade, hexagonal stone balcony slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'sidewalk street-side view of a 4th-floor balcony, sandstone historic facade, trapezoidal concrete balcony, classical balusters matching large brackets, see-through openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from across the street, looking up at a 5th-floor balcony with perspective, pale blue apartment facade, white concrete balcony, classical masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'low-angle street photo of a 6th-floor balcony, strong upward perspective, terracotta tiled facade accents, semicircular concrete balcony, heavy posts and geometric precast grille openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'medium facade crop from the sidewalk of a 7th-floor balcony, limestone classical facade, slightly oval stone balcony, square posts and rectangular balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'street-side medium shot of a 8th-floor balcony, beige stucco facade, rectangular concrete slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'street view facade crop of a 9th-floor balcony, grey concrete facade, slightly elliptical stone balcony, classical balusters matching cornice and brackets, openings between posts, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from the sidewalk looking up at a 10th-floor balcony, strong perspective foreshortening, red brick facade, semicircular concrete balcony, square posts and rectangular balusters with clear open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'street-level sidewalk looking upward toward a 2nd-floor balcony, tall facade perspective, white painted facade, elliptical limestone balcony, ornate classical balusters, open voids between balusters, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'angled street photo looking up at a 3rd-floor balcony, perspective foreshortening, ochre plaster facade, triangular-plan concrete balcony, thick posts with pierced precast panel openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'frontal street crop of a 4th-floor balcony, dark charcoal modern facade, hexagonal stone balcony slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'sidewalk street-side view of a 5th-floor balcony, sandstone historic facade, trapezoidal concrete balcony, classical balusters matching large brackets, see-through openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from across the street, looking up at a 6th-floor balcony with perspective, pale blue apartment facade, white concrete balcony, classical masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'low-angle street photo of a 7th-floor balcony, strong upward perspective, terracotta tiled facade accents, semicircular concrete balcony, heavy posts and geometric precast grille openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'medium facade crop from the sidewalk of a 8th-floor balcony, limestone classical facade, slightly oval stone balcony, square posts and rectangular balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'street-side medium shot of a 9th-floor balcony, beige stucco facade, rectangular concrete slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'street view facade crop of a 10th-floor balcony, grey concrete facade, slightly elliptical stone balcony, classical balusters matching cornice and brackets, openings between posts, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from the sidewalk looking up at a 2nd-floor balcony, strong perspective foreshortening, red brick facade, semicircular concrete balcony, square posts and rectangular balusters with clear open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'street-level sidewalk looking upward toward a 3rd-floor balcony, tall facade perspective, white painted facade, elliptical limestone balcony, ornate classical balusters, open voids between balusters, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'angled street photo looking up at a 4th-floor balcony, perspective foreshortening, ochre plaster facade, triangular-plan concrete balcony, thick posts with pierced precast panel openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'frontal street crop of a 5th-floor balcony, dark charcoal modern facade, hexagonal stone balcony slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'sidewalk street-side view of a 6th-floor balcony, sandstone historic facade, trapezoidal concrete balcony, classical balusters matching large brackets, see-through openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from across the street, looking up at a 7th-floor balcony with perspective, pale blue apartment facade, white concrete balcony, classical masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'low-angle street photo of a 8th-floor balcony, strong upward perspective, terracotta tiled facade accents, semicircular concrete balcony, heavy posts and geometric precast grille openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'medium facade crop from the sidewalk of a 9th-floor balcony, limestone classical facade, slightly oval stone balcony, square posts and rectangular balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'street-side medium shot of a 10th-floor balcony, beige stucco facade, rectangular concrete slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'street view facade crop of a 2nd-floor balcony, grey concrete facade, slightly elliptical stone balcony, classical balusters matching cornice and brackets, openings between posts, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from the sidewalk looking up at a 3rd-floor balcony, strong perspective foreshortening, red brick facade, semicircular concrete balcony, square posts and rectangular balusters with clear open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'street-level sidewalk looking upward toward a 4th-floor balcony, tall facade perspective, white painted facade, elliptical limestone balcony, ornate classical balusters, open voids between balusters, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'angled street photo looking up at a 5th-floor balcony, perspective foreshortening, ochre plaster facade, triangular-plan concrete balcony, thick posts with pierced precast panel openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'frontal street crop of a 6th-floor balcony, dark charcoal modern facade, hexagonal stone balcony slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'sidewalk street-side view of a 7th-floor balcony, sandstone historic facade, trapezoidal concrete balcony, classical balusters matching large brackets, see-through openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from across the street, looking up at a 8th-floor balcony with perspective, pale blue apartment facade, white concrete balcony, classical masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'low-angle street photo of a 9th-floor balcony, strong upward perspective, terracotta tiled facade accents, semicircular concrete balcony, heavy posts and geometric precast grille openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'medium facade crop from the sidewalk of a 10th-floor balcony, limestone classical facade, slightly oval stone balcony, square posts and rectangular balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'street-side medium shot of a 2nd-floor balcony, beige stucco facade, rectangular concrete slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'street view facade crop of a 3rd-floor balcony, grey concrete facade, slightly elliptical stone balcony, classical balusters matching cornice and brackets, openings between posts, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from the sidewalk looking up at a 4th-floor balcony, strong perspective foreshortening, red brick facade, semicircular concrete balcony, square posts and rectangular balusters with clear open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'street-level sidewalk looking upward toward a 5th-floor balcony, tall facade perspective, white painted facade, elliptical limestone balcony, ornate classical balusters, open voids between balusters, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'angled street photo looking up at a 6th-floor balcony, perspective foreshortening, ochre plaster facade, triangular-plan concrete balcony, thick posts with pierced precast panel openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
    'frontal street crop of a 7th-floor balcony, dark charcoal modern facade, hexagonal stone balcony slab, square masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, overcast daylight',
    'sidewalk street-side view of a 8th-floor balcony, sandstone historic facade, trapezoidal concrete balcony, classical balusters matching large brackets, see-through openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, clear afternoon light',
    'from across the street, looking up at a 9th-floor balcony with perspective, pale blue apartment facade, white concrete balcony, classical masonry balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, soft morning light',
    'low-angle street photo of a 10th-floor balcony, strong upward perspective, terracotta tiled facade accents, semicircular concrete balcony, heavy posts and geometric precast grille openings, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, diffuse cloudy light',
    'medium facade crop from the sidewalk of a 2nd-floor balcony, limestone classical facade, slightly oval stone balcony, square posts and rectangular balusters with open gaps, upper-story balcony unit, full window visible behind the railing, medium facade crop, street-side exterior only, not from on the balcony, not a railing-only close-up, bright daylight with soft shadows',
]

NEGATIVE_PROMPT = (
    'ground-floor porch, entrance stoop only, first-floor patio at street level, '
    'view from on the balcony looking out, indoor terrace view, '
    'extreme close-up of railing only, railing fills the frame, cropped window, '
    'tight zoom on balusters, macro detail shot, '
    'solid closed wall between posts, no openings, blank panel, '
    'metal rails, thin steel rods, glass panel, wrought iron, '
    'cartoon, blurry'
)

